Resources:
  - Name: PDPVerifier
    Address: "0x58B1b601eE88044f5a7F56b3ABEC45FAa7E7681B"
    Triggers:
      - Type: "event"
        Definition: "ProofSetCreated(uint256 indexed setId, address indexed owner)"
        Handler: "ProofSetCreatedHandler"

      - Type: "event"
        Definition: "ProofSetOwnerChanged(uint256 indexed setId, address indexed oldOwner, address indexed newOwner)"
        Handler: "ProofSetOwnerChangedHandler"

      - Type: "event"
        Definition: "ProofSetDeleted(uint256 indexed setId, uint256 deletedLeafCount)"
        Handler: "ProofSetDeletedHandler"

      - Type: "event"
        Definition: "RootsAdded(uint256 indexed setId, uint256[] rootIds)"
        Handler: "RootsAddedHandler"

      - Type: "event"
        Definition: "RootsRemoved(uint256 indexed setId, uint256[] rootIds)"
        Handler: "RootsRemovedHandler"

      - Type: "event"
        Definition: "ProofFeePaid(uint256 indexed setId, uint256 fee, uint64 price, int32 expo)"
        Handler: "ProofFeePaidHandler"

      - Type: "event"
        Definition: "ProofSetEmpty(uint256 indexed setId)"
        Handler: "ProofSetEmptyHandler"

      - Type: "event"
        Definition: "PossessionProven(uint256 indexed setId, (uint256, uint256)[] challenges)"
        Handler: "PossessionProvenHandler"

      - Type: "event"
        Definition: "NextProvingPeriod(uint256 indexed setId, uint256 challengeEpoch, uint256 leafCount)"
        Handler: "NextProvingPeriodHandler"

  - Name: PDPService
    Address: ""
    Triggers:
      - Type: "event"
        Definition: "FaultRecord(uint256 indexed proofSetId, uint256 periodsFaulted, uint256 deadline)"
        Handler: "FaultRecordHandler"
