Resources:
  - Name: PDPVerifier
    Address: ""
    Triggers:
      - Type: "event"
        Definition: "ProofSetCreated(uint256 setId)"
        Handler: "ProofSetCreatedHandler"

      - Type: "event"
        Definition: "ProofSetDeleted(uint256 setId)"
        Handler: "ProofSetDeletedHandler"

      - Type: "event"
        Definition: "RootsAdded(uint256 setId, uint256 firstAdded)"
        Handler: "RootsAddedHandler"

      - Type: "event"
        Definition: "RootsRemoved(uint256 setId, uint256 firstRemoved)"
        Handler: "RootsRemovedHandler"

      - Type: "event"
        Definition: "ProofFeePaid(uint256 indexed setId, uint256 fee, uint64 price, int32 expo)"
        Handler: "ProofFeePaidHandler"

      - Type: "event"
        Definition: "ProofSetEmpty(uint256 setId)"
        Handler: "ProofSetEmptyHandler"

  - Name: PDPService
    Address: ""
    Triggers:
      - Type: "event"
        Definition: "FaultRecord(uint256 indexed proofSetId, uint256 periodsFaulted, uint256 deadline)"
        Handler: "FaultRecordHandler"

  - Name: WFIL
    Address: "0x60E1773636CF5E4A227d9AC24F20fEca034ee25A"
    Triggers:
      - Type: "event"
        Definition: "Transfer(address indexed from, address indexed to, uint256 value)"
        Handler: "TransferHandler"
      - Type: "function"
        Definition: "transfer(address,uint256)"
        Handler: "TransferFunctionHandler"
