interface ImportMeta {
  env: {
    VITE_MAINNET_PDP_VERIFIER: string;
    VITE_MAINNET_PDP_SERVICE: string;
    VITE_CALIBRATION_PDP_VERIFIER: string;
    VITE_CALIBRATION_PDP_SERVICE: string;
    VITE_SUBGRAPH_URL_MAINNET: string;
    VITE_SUBGRAPH_URL_CALIBRATION: string;
  };
}
